Chore/secondary notebook toolbar tests (#17)
* added unit-tests for the secondary notebook toolbar

* added automatic test-report upload

* included passed tests with test report

* added test-results to PR comments

* gave build-workflow permission to edit the PR

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -10,6 +10,10 @@ concurrency:
   group: ${{ github.workflow }}-${{ github.event.pull_request.number || github.ref }}
   cancel-in-progress: true
 
+permissions:
+  checks: write
+  pull-requests: write
+
 jobs:
   build:
     runs-on: ubuntu-latest
@@ -34,6 +38,15 @@ jobs:
       run: |
         set -eux
         jlpm run test
+
+    - name: Publish Test Report
+      id: report
+      uses: mikepenz/action-junit-report@v6
+      if: success() || failure() # always run even if the previous step fails
+      with:
+        report_paths: 'junit.xml'
+        include_passed: 'true'
+        comment: 'true'
 
     - name: Build the extension
       run: |
